// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoAPI.Data;

#nullable disable

namespace ProyectoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320114609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ProyectoAPI.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Imagen = "/imagenes/teclado.jpg",
                            Nombre = "Teclado",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Imagen = "/imagenes/raton.jpg",
                            Nombre = "Ratón",
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            Imagen = "/imagenes/monitor.jpg",
                            Nombre = "Monitor",
                            Stock = 8
                        },
                        new
                        {
                            Id = 4,
                            Imagen = "/imagenes/impresora.jpg",
                            Nombre = "Impresora",
                            Stock = 5
                        },
                        new
                        {
                            Id = 5,
                            Imagen = "/imagenes/altavoces.jpg",
                            Nombre = "Altavoces",
                            Stock = 12
                        },
                        new
                        {
                            Id = 6,
                            Imagen = "/imagenes/webcam.jpg",
                            Nombre = "Webcam",
                            Stock = 18
                        },
                        new
                        {
                            Id = 7,
                            Imagen = "/imagenes/microfono.jpg",
                            Nombre = "Micrófono",
                            Stock = 7
                        },
                        new
                        {
                            Id = 8,
                            Imagen = "/imagenes/portatil.jpg",
                            Nombre = "Portátil",
                            Stock = 4
                        },
                        new
                        {
                            Id = 9,
                            Imagen = "/imagenes/tablet.jpg",
                            Nombre = "Tablet",
                            Stock = 9
                        },
                        new
                        {
                            Id = 10,
                            Imagen = "/imagenes/discoduro.jpg",
                            Nombre = "Disco Duro",
                            Stock = 15
                        },
                        new
                        {
                            Id = 11,
                            Imagen = "/imagenes/memoriausb.jpg",
                            Nombre = "Memoria USB",
                            Stock = 30
                        },
                        new
                        {
                            Id = 12,
                            Imagen = "/imagenes/router.jpg",
                            Nombre = "Router",
                            Stock = 6
                        },
                        new
                        {
                            Id = 13,
                            Imagen = "/imagenes/switch.jpg",
                            Nombre = "Switch",
                            Stock = 11
                        },
                        new
                        {
                            Id = 14,
                            Imagen = "/imagenes/proyector.jpg",
                            Nombre = "Proyector",
                            Stock = 3
                        },
                        new
                        {
                            Id = 15,
                            Imagen = "/imagenes/camara.jpg",
                            Nombre = "Cámara",
                            Stock = 14
                        },
                        new
                        {
                            Id = 16,
                            Imagen = "/imagenes/smartphone.jpg",
                            Nombre = "Smartphone",
                            Stock = 20
                        },
                        new
                        {
                            Id = 17,
                            Imagen = "/imagenes/auriculares.jpg",
                            Nombre = "Auriculares",
                            Stock = 22
                        },
                        new
                        {
                            Id = 18,
                            Imagen = "/imagenes/cable hdmi.jpg",
                            Nombre = "Cable HDMI",
                            Stock = 40
                        },
                        new
                        {
                            Id = 19,
                            Imagen = "/imagenes/cableusb.jpg",
                            Nombre = "Cable USB",
                            Stock = 35
                        },
                        new
                        {
                            Id = 20,
                            Imagen = "/imagenes/tarjetagrafica.jpg",
                            Nombre = "Tarjeta Gráfica",
                            Stock = 2
                        },
                        new
                        {
                            Id = 21,
                            Imagen = "/imagenes/fuentedepoder.jpg",
                            Nombre = "Fuente de Poder",
                            Stock = 6
                        },
                        new
                        {
                            Id = 22,
                            Imagen = "/imagenes/placabase.jpg",
                            Nombre = "Placa Base",
                            Stock = 5
                        },
                        new
                        {
                            Id = 23,
                            Imagen = "/imagenes/procesador.jpg",
                            Nombre = "Procesador",
                            Stock = 7
                        },
                        new
                        {
                            Id = 24,
                            Imagen = "/imagenes/memoriaram.jpg",
                            Nombre = "Memoria RAM",
                            Stock = 16
                        },
                        new
                        {
                            Id = 25,
                            Imagen = "/imagenes/ssd.jpg",
                            Nombre = "SSD",
                            Stock = 13
                        },
                        new
                        {
                            Id = 26,
                            Imagen = "/imagenes/sillagaming.jpg",
                            Nombre = "Silla Gaming",
                            Stock = 4
                        },
                        new
                        {
                            Id = 27,
                            Imagen = "/imagenes/mesa escritorio.jpg",
                            Nombre = "Mesa Escritorio",
                            Stock = 3
                        },
                        new
                        {
                            Id = 28,
                            Imagen = "/imagenes/lamparaled.jpg",
                            Nombre = "Lámpara LED",
                            Stock = 17
                        },
                        new
                        {
                            Id = 29,
                            Imagen = "/imagenes/regleta.jpg",
                            Nombre = "Regleta",
                            Stock = 21
                        },
                        new
                        {
                            Id = 30,
                            Imagen = "/imagenes/adaptador.jpg",
                            Nombre = "Adaptador",
                            Stock = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
